#! /bin/sh

# Melicia unknown command
#xsetroot -cursor_name left_ptr &

#### -- AutoStart -- ####
sxhkd &
compton &
nitrogen --restore &
~/.config/bspwm/panel.sh &



#### -- Monitors -- ####
bspc monitor -d I II III IV V VI VII VIII IX X
# 1 2 3 4 5 6 7 8 9 10

#### -- Apperance -- ####

# Define window padding
bspc config border_width         2
bspc config window_gap          12

# Melicia window padding
#bspc config border_width         0
#bspc config top_padding 	    -15
#bspc config right_padding	    -15
#bspc config left_padding       -15
#bspc config bottom_padding     -15
#bspc config window_gap          25


# Define window split ratio
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#Melicia split_ratio was 0.50


## -- bspc Rules -- ##
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Melicia colour scheme
#bspc config focused_border_color   "#0C2220"
#bspc config normal_border_color    "#0C2220"
#bspc config urgent_border_color    "#B58900"
#bspc config presel_border_color    "#26E2FF"

# melicia polybar launch
$XDG_CONFIG_HOME/polybar/launch.sh
